### ISSUE TITLE
build using ghc 8.4.2 with pedantic fails

### ISSUE THREAD

**Issue by pjljvandelaar** [capitanbatata/text-via-sockets#3]
I get:

```
    ←[;1msrc\Network\TextViaSockets.hs:52:1: ←[;1m←[31merror:←[0m←[0m←[;1m [←[;1m←[31m-Wunus
mports←[0m←[0m←[;1m]←[0m←[0m←[;1m
        The import of `Data.Monoid' is redundant
          except perhaps to import instances from `Data.Monoid'
        To import instances alone, use: import Data.Monoid()←[0m←[0m
    ←[;1m←[34m   |←[0m←[0m
    ←[;1m←[34m52 |←[0m←[0m ←[;1m←[31mimport           Data.Monoid←[0m←[0m
    ←[;1m←[34m   |←[0m←[0m←[;1m←[31m ^^^^^^^^^^^^^^^^^^^^^^^^^^^^←[0m←[0m
    ←[0m←[0m←[0m
```

**Comment by pjljvandelaar** [comment]
Similar with 8.6.4
```
   [1 of 2] Compiling Network.TextViaSockets ( src\Network\TextViaSockets.hs, .stack-work\dist\e626a42b\build\Network\TextViaSockets.o )

    src\Network\TextViaSockets.hs:52:1: error: [-Wunused-imports, -Werror=unused-imports]
        The import of `Data.Monoid' is redundant
          except perhaps to import instances from `Data.Monoid'
        To import instances alone, use: import Data.Monoid()
       |
    52 | import           Data.Monoid
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    src\Network\TextViaSockets.hs:111:31: error: [-Wdeprecations, -Werror=deprecations]
        In the use of `iNADDR_ANY' (imported from Network.Socket):
        Deprecated: "Use getAddrInfo instead"
        |
    111 |     bind sock (SockAddrInet p iNADDR_ANY)
        |                               ^^^^^^^^^^

    src\Network\TextViaSockets.hs:131:29: error: [-Wdeprecations, -Werror=deprecations]
        In the use of `aNY_PORT' (imported from Network.Socket):
        Deprecated: "Use defaultPort instead"
        |
    131 |     bind sock (SockAddrInet aNY_PORT iNADDR_ANY)
        |                             ^^^^^^^^

    src\Network\TextViaSockets.hs:131:38: error: [-Wdeprecations, -Werror=deprecations]
        In the use of `iNADDR_ANY' (imported from Network.Socket):
        Deprecated: "Use getAddrInfo instead"
        |
    131 |     bind sock (SockAddrInet aNY_PORT iNADDR_ANY)
        |                                      ^^^^^^^^^^

    src\Network\TextViaSockets.hs:248:15: error: [-Wdeprecations, -Werror=deprecations]
        In the use of data constructor `MkSocket'
        (imported from Network.Socket, but defined in network-2.8.0.0:Network.Socket.Types):
        Deprecated: "'MkSocket' will not be available in version 3.0.0.0 or later. Use fdSocket instead"
        |
    248 |           let MkSocket _ _ _ _ stMV = sock
        |               ^^^^^^^^

    src\Network\TextViaSockets.hs:251:15: error: [-Wdeprecations, -Werror=deprecations]
        In the use of data constructor `Closed'
        (imported from Network.Socket, but defined in network-2.8.0.0:Network.Socket.Types):
        Deprecated: "SocketStatus will be removed"
        |
    251 |               Closed -> return ()
        |               ^^^^^^

```
